
name: Reminder Deployment Pipeline

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deployment
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/zc_plugin_reminder/
            rm -rf .
            git clone https://github.com/zurichat/zc_plugin_reminder.git . --branch master
            touch .env
            echo MONGO_DB_URL=${{secrets.MONGO_DB_URL}} >> .env
            echo PORT=${{secrets.PORT}} >> .env
            cat .env
            yarn holoInstall
            yarn build
            yarn start
